package com.idohoo.user.protocol.req;

import com.idohoo.user.protocol.UserMicroServiceProperty;

import java.util.Date;

public class UserInsertMsReq implements UserMicroServiceProperty {

    public static final String URI = "/ms/user/insert.do";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private String nick_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_level_id
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private Integer user_level_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private String email;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone=phone;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password=password;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name=user_name;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name=nick_name;
    }

    public Integer getUser_level_id() {
        return user_level_id;
    }

    public void setUser_level_id(Integer user_level_id) {
        this.user_level_id=user_level_id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email=email;
    }
}