package com.idohoo.user.protocol.req;

import com.idohoo.user.protocol.UserMicroServiceProperty;

public class UserDeleteMsReq implements UserMicroServiceProperty {

    public static final String URI = "/ms/user/delete.do";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private Integer user_id;

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id=user_id;
    }
}