package com.idohoo.front.vo.inputVO;

public class UserIdInputVO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sun Jun 11 16:28:01 CST 2017
     */
    private Integer user_id;

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id=user_id;
    }
}